Unbreak blocking_con
edgedb/edgedb-python pull request #134
Opened 2020-12-06 04:16 UTC by elprans

Changes in #132 modified the internal API, but `blocking_con` wasn't
updated.  Rectify that.

2020-12-06 21:28 UTC, 1st1 approved these changes

2020-12-07 10:56 UTC, tailhook requested changes
It's done [here](https://github.com/edgedb/edgedb-python/blob/ecd15f1faf56f05a224a75edfefb4526b814e7a8/edgedb/protocol/blocking_proto.pyx#L91-L95) as we don't expose extra APIs into sync bindings. I think we have sync tests so they would have shown this issue.

Anything that actually breaks for you?

2020-12-07 15:37 UTC, elprans commented
> Anything that actually breaks for you?

Yes. Without this change tests break and all those methods return a tuple.

2020-12-07 16:05 UTC, elprans commented
Oh, I think this was a case of Cython not recompiling the *.c file.  The `Makefile` should probably just `rm *.c`, like we do in the server.

2020-12-07 16:05 UTC, closed without merging